### ISSUE TITLE
java.io.EOFException creating a FileObjectQueue

### ISSUE THREAD

**Issue by jzonthemtn** [square/tape#125]
I feel like I am doing something wrong. I get the following exception when trying to create a `FileObjectQueue`:

```
java.io.EOFException
        at java.io.RandomAccessFile.readFully(Unknown Source) ~[?:1.8.0_92]
        at java.io.RandomAccessFile.readFully(Unknown Source) ~[?:1.8.0_92]
        at com.squareup.tape.QueueFile.readHeader(QueueFile.java:160) ~[tape-1.2.3.jar!/:?]
        at com.squareup.tape.QueueFile.<init>(QueueFile.java:117) ~[tape-1.2.3.jar!/:?]
        at com.squareup.tape.FileObjectQueue.<init>(FileObjectQueue.java:35) ~[tape-1.2.3.jar!/:?]
```

I'm trying to use a temporary file for the queue:

`File file = File.createTempFile(System.getProperty("java.io.tmpdir"), UUID.randomUUID().toString());`

And then I create the queue:

`ObjectQueue<Message> queue = new FileObjectQueue<Message>(file, new GsonConverter<Message>(gson, Message.class));`

I changed to the `InMemoryObjectQueue` and it works fine. I'm using Java 8 and currently on a Windows VM at the moment. I'm using version 1.2.3. Any ideas what I could be doing wrong? Thanks

**Comment by paulo-raca** [comment]
`File.createTempFile()` creates a an empty file.
FileObjectQueue will initialize a file if it doesn't yet exist, but an empty file is treated as an error.

Everything should be OK if you execute `file.delete()` before initializing the queue

**Comment by jzonthemtn** [comment]
Ah! Thank you!
