### ISSUE TITLE
Invalid argument when RandomAccessFile is too big

### ISSUE THREAD

**Issue by tomjamescn** [square/tape#150]
when RandomAccessFile is too big , for example 1 G:

java.io.IOException: Invalid argument
	at java.io.RandomAccessFile.setLength(Native Method) ~[na:1.8.0_111]
	at com.squareup.tape.QueueFile.setLength(QueueFile.java:406) ~[canalClient-1.0-SNAPSHOT.jar:na]
	at com.squareup.tape.QueueFile.expandIfNecessary(QueueFile.java:375) ~[canalClient-1.0-SNAPSHOT.jar:na]
	at com.squareup.tape.QueueFile.add(QueueFile.java:305) ~[canalClient-1.0-SNAPSHOT.jar:na]
	at com.squareup.tape.QueueFile.add(QueueFile.java:287) ~[canalClient-1.0-SNAPSHOT.jar:na]
	at com.haibian.util.FileChannel.add(FileChannel.java:41) ~[canalClient-1.0-SNAPSHOT.jar:na]
	at com.haibian.AbstractCanalClient.process(AbstractCanalClient.java:168) ~[canalClient-1.0-SNAPSHOT.jar:na]
	at com.haibian.AbstractCanalClient$2.run(AbstractCanalClient.java:73) [canalClient-1.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by jan-zajic** [comment]
+1, we have same:
09:32:16.976 [vert.x-eventloop-thread-1] ERROR olife.mqtt.TapeQueue -
java.io.IOException: Invalid argument
        at java.io.RandomAccessFile.setLength(Native Method)
        at com.squareup.tape.QueueFile.setLength(QueueFile.java:406)
        at com.squareup.tape.QueueFile.expandIfNecessary(QueueFile.java:375)
        at com.squareup.tape.QueueFile.add(QueueFile.java:305)
        at com.squareup.tape.QueueFile.add(QueueFile.java:287)
        at olife.mqtt.TapeQueue$1.write(TapeQueue.java:49)

**Comment by rabelenda** [comment]
+1, Same here. 

In my case the problem started when the file was at 1,073,741,824 bytes (1GB) size. Since the library uses ints for file sizes, offsets, etc, and it tries to double the size every time it fills the file, the length goes to 1,073,741,824*2=2,147,483,648 (2GB), which is greater than maximum int (2^31-1=2,147,483,647), in consequence you get a negative size (-2^31=-2,147,483,649) and lib fails trying to set the file size to a negative size.

One solution could be changing all ints in lib to longs, allowing up to 2^33-1 GB files, requiring change of file format. Another alternative might be making explicit the file size limitation (maybe including a warning in readme and webpage) and throw a more descriptive exception to client code.

**Comment by rabelenda** [comment]
+1, Same here, the problem should be fixed by https://github.com/square/tape/pull/127, which is already in master, any plans when is this going to be released?

**Comment by f2prateek** [comment]
It's released as a snapshot https://github.com/square/tape#download
