### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by wuyexiong** [square/tape#80]
I Need you suggest

Queue Info

```
FileObjectQueue >> FileObjectQueue{queueFile=QueueFile[fileLength=524288, size=94, first=Element[position = 16, length = 3198], last=Element[position = 280547, length = 271], element lengths=[3198, 2750, 2951, 3006, 2453, 2994, 2685, 2868, 2585, 2638, 2589, 2510, 2461, 3178, 2722, 3018, 2720, 2872, 2983, 3436, 3100, 3198, 2643, 2552, 2757, 3643, 3663, 3494, 3455, 3113, 3550, 3513, 3354, 3421, 3131, 2738, 2894, 3097, 2512, 2493, 2512, 2484, 2508, 2492, 1436, 2770, 2845, 2900, 2725, 3130, 2793, 3035, 2743, 2754, 2901, 3451, 3137, 3437, 3070, 3164, 3093, 3270, 3021, 3142, 3516, 3458, 3404, 3454, 3435, 3469, 3567, 1359, 3122, 2800, 2746, 1090, 2872, 2892, 3564, 3087, 3506, 3511, 3359, 3491, 3469, 3502, 3527, 3528, 3477, 3496, 3572, 3475, 2660, 271]]}
```

Error Log
```
java.lang.StackOverflowError
            at java.io.BufferedInputStream.read(BufferedInputStream.java:252)
            at libcore.io.Streams.readFully(Streams.java:81)
            at java.io.DataInputStream.readShort(DataInputStream.java:152)
            at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:165)
            at java.io.DataInputStream.readUTF(DataInputStream.java:169)
            at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:1707)
            at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1637)
            at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:658)
            at java.io.ObjectInputStream.readNewArray(ObjectInputStream.java:1421)
            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:760)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1988)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1945)
            at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1116)
            at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:455)
            at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1348)
            at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1245)
            at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1840)
            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:762)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1988)
            at java.io.ObjectInputStream.readUnshared(ObjectInputStream.java:1960)
            at com.squareup.tape.SerializedConverter.deserialize(SerializedConverter.java:27)
            at com.squareup.tape.SerializedConverter.from(SerializedConverter.java:38)
            at com.squareup.tape.SerializedConverter.from(SerializedConverter.java:20)
            at com.squareup.tape.FileObjectQueue.peek(FileObjectQueue.java:61)
            at com.squareup.tape.TaskQueue.peek(TaskQueue.java:29)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:49)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
            
```

**Comment by JakeWharton** [comment]
```
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
         at PerformanceRequestService.executeNext(PerformanceRequestService.java:52)
         at PerformanceRequestService.onSuccess(PerformanceRequestService.java:62)
         at PerformanceRequestTask.execute(PerformanceRequestTask.java:83)
```
Your task and service recursively calls into itself to execute the next task rather than using an iteration approach. After a certain amount of tasks this will _always_ trigger this error.

**Comment by wuyexiong** [comment]
got it, thanks a lot
