### ISSUE TITLE
What is the equivalent of poll or dequeue method

### ISSUE THREAD

**Issue by mozinrat** [square/tape#87]
What to do if one need to consume the queue also. Trying to do pub-sub using this.
I know we can easily write one using queue.remove. Still I believe it would be quick task but add meaning to lib.

**Comment by mozinrat** [comment]
Exception in thread "Thread-3" Exception in thread "Thread-4" com.squareup.tape.FileException: Failed to peek.
	at com.squareup.tape.FileObjectQueue.peek(FileObjectQueue.java:59)
	at com.example.FileQueueConsumer.run(FileQueueConsumer.java:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.StreamCorruptedException: invalid type code: AC
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1381)
	at java.io.ObjectInputStream.readUnshared(ObjectInputStream.java:463)
	at com.squareup.tape.SerializedConverter.deserialize(SerializedConverter.java:27)
	at com.squareup.tape.SerializedConverter.from(SerializedConverter.java:37)
	at com.squareup.tape.SerializedConverter.from(SerializedConverter.java:20)
	at com.squareup.tape.FileObjectQueue.peek(FileObjectQueue.java:57)
	... 3 more
Here is what I did?
Create producer1, producer2,consumer1,consumer2 all on same FileObjectQueue. I believe there is some issue in multithreading handling.

**Comment by f2prateek** [comment]
FileObjectQueue is [not thread safe](https://github.com/square/tape/blob/master/tape/src/main/java/com/squareup/tape/FileObjectQueue.java#L16-L17).

**Comment by mozinrat** [comment]
Is there a threadsafe file based queue in the current api?

**Comment by JakeWharton** [comment]
No
